### ISSUE TITLE
Invalid path on Windows 11 when cloning repo

### ISSUE THREAD

**Issue by CheezeCoder** [VectorPanic/rune-sdk#1]
When cloning the repo on windows 11 with git I get the following error:

```bash
error: invalid path 'docs/JSDoc: Class: URLLoader.html'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Looking further into this issue it appears to be an issue with file naming and a security fix years ago with NTFS files.  You can see a discourse about it here : https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows

Following the advice and disabling core.protectNTFS flag allows the repo to be checked out but it still won't accept the file in question, namely :  docs/JSDoc: Class: URLLoader.html.  

When completing the checkout i am presented with the following error:

```bash
$ git checkout
error: unable to create file docs/JSDoc: Class: URLLoader.html: Invalid argument
D       docs/JSDoc: Class: URLLoader.html
Your branch is up to date with 'origin/main'.
```

So it gets me almost all the way there.  Is there perhaps another name that can be used with the file?  This way I can reenable to the NTFS flag which is probably a good idea anyways.

Thanks!

**Comment by VectorPanic** [comment]
The error should now be resolved. JSDoc seems to have exported a class (`rune.net.URLLoader`) with the wrong filename. A new version of the documentation has been generated, and this hopefully resolves the issue.

**Comment by CheezeCoder** [comment]
Brilliant works great! Thanks for the quick fix!
